config/routes.rb
Rails.application.routes.draw do

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  root to: "catalog#index"
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/search', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable

  end
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/view', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/catalog_controller.rb
# frozen_string_literal: true
class CatalogController < ApplicationController

  include Blacklight::Catalog
  include BlacklightRangeLimit::ControllerOverride


  breakline_options = {
    two_words_connector: '<br />',
    words_connector: '<br />',
    last_word_connector: '<br />'
  }


  configure_blacklight do |config|

    # can't prevent storing searches (serialized query params) in db if we want prev/next document on item-view page
    # at least don't store the queries for bots
    # see https://github.com/projectblacklight/blacklight/pull/1736#issuecomment-335977563
    config.crawler_detector = lambda { |req| req.is_crawler? }

    ## Class for sending and receiving requests from a search index
    # config.repository_class = Blacklight::Solr::Repository
    #
    ## Class for converting Blacklight's url parameters to into request parameters for the search index
    # config.search_builder_class = ::SearchBuilder
    #
    ## Model that maps search index responses to the blacklight response model
    # config.response_model = Blacklight::Solr::Response
    #
    ## Should the raw solr document endpoint (e.g. /catalog/:id/raw) be enabled
    # config.raw_endpoint.enabled = false

    ## Default parameters to send to solr for all search-like requests. See also SearchBuilder#processed_parameters
    config.default_solr_params = {
      rows: 10
    }

    # solr path which will be added to solr base url before the other solr params.
    #config.solr_path = 'select'
    #config.document_solr_path = 'get'
    config.document_solr_request_handler = 'document'
    config.document_solr_path = 'select'
    config.document_unique_id_param = 'id'

    # items to show per page, each number in the array represent another option to choose from.
    #config.per_page = [10,20,50,100]

    # solr field configuration for search results/index views
    config.index.title_field = 'displayName'
    #config.index.display_type_field = 'format'
    #config.index.thumbnail_field = 'thumbnail_path_ss'

    config.add_results_document_tool(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)

    config.add_results_collection_tool(:sort_widget)
    config.add_results_collection_tool(:per_page_widget)
    config.add_results_collection_tool(:view_type_group)

    # TODO investigate these
    #config.add_show_tools_partial(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)
    #config.add_show_tools_partial(:email, callback: :email_action, validator: :validate_email_params)
    #config.add_show_tools_partial(:sms, if: :render_sms_action?, callback: :sms_action, validator: :validate_sms_params)
    #config.add_show_tools_partial(:citation)

    #config.add_nav_action(:bookmark, partial: 'blacklight/nav/bookmark', if: :render_bookmarks_control?)
    #config.add_nav_action(:search_history, partial: 'blacklight/nav/search_history')

    # solr field configuration for document/show views
    #config.show.title_field = 'title_tsim'
    #config.show.display_type_field = 'format'
    #config.show.thumbnail_field = 'thumbnail_path_ss'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    #
    # set :index_range to true if you want the facet pagination view to have facet prefix-based navigation
    #  (useful when user clicks "more" on a large facet and wants to navigate alphabetically across a large set of results)
    # :index_range can be an array or range of prefixes that will be used to create the navigation (note: It is case sensitive when searching values)

    # config.add_facet_field 'format', label: 'Format'
    # config.add_facet_field 'pub_date_ssim', label: 'Publication Year', single: true
    # config.add_facet_field 'subject_ssim', label: 'Topic', limit: 20, index_range: 'A'..'Z'
    # config.add_facet_field 'language_ssim', label: 'Language', limit: true
    # config.add_facet_field 'lc_1letter_ssim', label: 'Call Number'
    # config.add_facet_field 'subject_geo_ssim', label: 'Region'
    # config.add_facet_field 'subject_era_ssim', label: 'Era'
    #
    # config.add_facet_field 'example_pivot_field', label: 'Pivot Field', pivot: ['format', 'language_ssim'], collapsing: true
    #
    # config.add_facet_field 'example_query_facet_field', label: 'Publish Date', :query => {
    #   :years_5 => { label: 'within 5 Years', fq: "pub_date_ssim:[#{Time.zone.now.year - 5 } TO *]" },
    #   :years_10 => { label: 'within 10 Years', fq: "pub_date_ssim:[#{Time.zone.now.year - 10 } TO *]" },
    #   :years_25 => { label: 'within 25 Years', fq: "pub_date_ssim:[#{Time.zone.now.year - 25 } TO *]" }
    # }
    # LINDAT
    config.add_facet_field 'contributor_ssim', label: 'Contributor',  limit: true, prefix_search: true
    config.add_facet_field 'coverage_ssim', label: 'Coverage',  limit: true, prefix_search: true
    config.add_facet_field 'creator_ssim', label: 'Creator', limit: true, prefix_search: true
    config.add_facet_field 'format', label: 'Format',  limit: true, prefix_search: true
    config.add_facet_field 'language_ssim', label: 'Language',  limit: true, prefix_search: true
    config.add_facet_field 'publisher_ssim', label: 'Publisher',  limit: true, prefix_search: true
    config.add_facet_field 'rights', label: 'Rights',  limit: true, prefix_search: true
    config.add_facet_field 'subject_ssim', label: 'Subject',  limit: true, prefix_search: true
    config.add_facet_field 'type_ssim', label: 'Type',  limit: true, prefix_search: true
    config.add_facet_field 'date_itsim', label: 'Date', range: true
    config.add_facet_field 'metadataOnly', label: 'Original context has metadata only', single: true
    ### these two are here for the pivot field to work
    config.add_facet_field 'harvestedFrom', label: 'Harvested from', show: false, limit: -1
    config.add_facet_field 'dataProvider_ssi', label: 'Data provider', show: false, limit: -1
    ### ///
    config.add_facet_field 'provider_pivot_field', label: 'Harvested from', pivot: [:harvestedFrom, :dataProvider_ssi], collapsing: true


    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    # config.add_index_field 'title_tsim', label: 'Title'
    # config.add_index_field 'title_vern_ssim', label: 'Title'
    # config.add_index_field 'author_tsim', label: 'Author'
    # config.add_index_field 'author_vern_ssim', label: 'Author'
    # config.add_index_field 'format', label: 'Format'
    # config.add_index_field 'language_ssim', label: 'Language'
    # config.add_index_field 'published_ssim', label: 'Published'
    # config.add_index_field 'published_vern_ssim', label: 'Published'
    # config.add_index_field 'lc_callnum_ssim', label: 'Call number'

    config.add_index_field 'creator_ssim', label: 'Creator', link_to_facet: true
    config.add_index_field 'publisher_ssim', label: 'Publisher', link_to_facet: true
    config.add_index_field 'format', label: 'Format', link_to_facet: true
    config.add_index_field 'type_ssim', label: 'Type', link_to_facet: true
    config.add_index_field 'subject_ssim', label: 'Subject', link_to_facet: true
    config.add_index_field 'language_ssim', label: 'Language', link_to_facet: true
    config.add_index_field 'description_tsim', label: 'Description'
    config.add_index_field 'rights', label: 'Rights', link_to_facet: true

    # TODO hasfiles???
    # TODO provider

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display
    # config.add_show_field 'title_vern_ssim', label: 'Title'
    # config.add_show_field 'subtitle_tsim', label: 'Subtitle'
    # config.add_show_field 'subtitle_vern_ssim', label: 'Subtitle'
    # config.add_show_field 'author_vern_ssim', label: 'Author'
    # config.add_show_field 'url_fulltext_ssim', label: 'URL'
    # config.add_show_field 'url_suppl_ssim', label: 'More Information'
    # config.add_show_field 'published_ssim', label: 'Published'
    # config.add_show_field 'published_vern_ssim', label: 'Published'
    # config.add_show_field 'lc_callnum_ssim', label: 'Call number'
    # config.add_show_field 'isbn_ssim', label: 'ISBN'
    # LINDAT
    config.add_show_field 'title_tsim', label: 'Title', separator_options: breakline_options
    config.add_show_field 'creator_ssim', label: 'Creator', link_to_facet: true
    config.add_show_field 'contributor_ssim', label: 'Contributor', link_to_facet: true
    config.add_show_field 'publisher_ssim', label: 'Publisher', link_to_facet: true

app/views/catalog/_facet_limit.html.erb
<%
  presenter = facet_field_presenter(facet_field, display_facet)
%>
<%= render Blacklight::PrefixSearch.new(facet_field_presenter: presenter) unless presenter.in_modal? %>
<%= render(Blacklight::FacetFieldListComponent.new(
      facet_field: presenter,
      layout: false)) %>

app/views/catalog/_home_text.html.erb
<h2>Catalog of resources available in LINDAT/CLARIAH-CZ</h2>

<p>This catalog contains metadata harvested from members of LINDAT/CLARIAH-CZ. You can use the search box above or the
  filters to explore the metadata. Every item should contain a link to the original source, where you should be able to
  gather more information about the particular resource.
</p>
<p>Metadata related issues can be reported at <a href="https://github.com/ufal/lindat-catalog-metadata/issues">lindat-catalog-metadata issue tracker</a>.</p>

<small>The catalog is running on <a href="https://github.com/projectblacklight/blacklight">project blacklight</a>,
  the icons used in single item view in "original context" menu are used under the following <a href="https://fontawesome.com/license/free">license</a></small>

app/views/catalog/_show_main_content.html.erb
<%= render(Blacklight::SearchContextComponent.new(search_context: @search_context, search_session: search_session)) if search_session['document_id'] == @document.id %>

<% @page_title = t('blacklight.search.show.title', document_title: Deprecation.silence(Blacklight::BlacklightHelperBehavior) { document_show_html_title }, application_name: application_name).html_safe %>
<% content_for(:head) { render_link_rel_alternates } %>

<%= render (blacklight_config.view_config(:show).document_component || Blacklight::DocumentComponent).new(presenter: document_presenter(@document), component: :div, title_component: :h1, show: true) do |component| %>
  <% component.footer do %>
    <% if @document.respond_to?(:export_as_openurl_ctx_kev) %>
      <!--
           // COinS, for Zotero among others.
           // This document_partial_name(@document) business is not quite right,
           // but has been there for a while.
      -->
      <span class="Z3988" title="<%= @document.export_as_openurl_ctx_kev(Deprecation.silence(Blacklight::RenderPartialsHelperBehavior) { document_partial_name(@document) }) %>"></span>
    <% end %>
  <%  end %>

  <%# Use :body for complete backwards compatibility (overriding the component body markup),
        but if the app explicitly  opted-in to components, make the partials data available as :partials to ease migrations pain %>
  <% component.public_send(blacklight_config.view_config(:show).document_component.blank? && blacklight_config.view_config(:show).partials.any? ? :body : :partial) do %>
    <div id="doc_<%= @document.id.to_s.parameterize %>">
      <%= render_document_partials @document, blacklight_config.view_config(:show).partials, component: component %>
    </div>
    <div class="alert alert-primary">The item or associated files might be "in copyright"; review the provided rights metadata:
      <ul>
      <% @document['rights'].each do |rights| %>
          <li><%= linkify(rights) %></li>
      <% end %>
      </ul>
      and the original context.
    </div>
  <% end %>
<% end %>

app/views/catalog/_show_sidebar.html.erb
<%= render 'show_tools' %>
<%= render(Blacklight::Document::MoreLikeThisComponent.new(document: document)) %>
<div class="card show-tools">
  <div class="card-header">
    <h2 class="mb-0 h6"><%= t('blacklight.sidebar.original_context') %></h2>
  </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= blacklight_icon('fa_cc_by_4.0_international/home-solid') %>
          <%= link_to "Show original", @document[:landingPage] %>
        </li>
        <li class="list-group-item">
          <%= blacklight_icon('fa_cc_by_4.0_international/eye-solid') %>
          <%= link_to "Show harvested metadata", solr_document_path(@document) + ".xml" %>
        </li>
    </ul>
</div>

app/views/catalog/facet.html.erb
<%= render Blacklight::System::ModalComponent.new do |component| %>
  <% component.prefix do %>
    <div class="facet-pagination top row justify-content-between">
      <%= render :partial=>'facet_pagination' %>
    </div>
  <% end %>

  <% component.title { facet_field_label(@facet.key) } %>

  <%= render partial: 'facet_index_navigation' if @facet.index_range && @display_facet.index? %>

  <%= render Blacklight::PrefixSearch.new(facet_field_presenter: facet_field_presenter(@facet, @display_facet)) %>

  <div class="facet-extended-list">
    <%= render_facet_limit(@display_facet, layout: false) %>
  </div>

  <% component.footer do %>
    <div class="facet-pagination bottom row justify-content-between">
      <%= render :partial=>'facet_pagination' %>
    </div>
  <% end %>
<% end %>